### ISSUE TITLE
Website Looks Bad

### ISSUE THREAD

**Issue by uellenberg** [radi-cho/awesome-gpt4#22]
![image](https://github.com/radi-cho/awesome-gpt4/assets/66662148/f1f17e64-074a-41e9-a8f8-66dd68ae304b)

I'd recommend taking a look at https://perfectmotherfuckingwebsite.com/ (https://github.com/LeoColomb/perfectmotherfuckingwebsite). It's a joke website, granted, but it gives good and simple advice on how to improve the styling of a site with fairly minimal effort. There's a lot that can be done with CSS, of course, but just copy-pasting in a style like this makes it look much nicer.

![image](https://github.com/radi-cho/awesome-gpt4/assets/66662148/5ee14e98-e848-4524-bec5-98d0a2293435)

**Comment by radi-cho** [comment]
True. The current website is just the markdown converted to plain HTML. Would you like to contribute by adding some styles to https://github.com/radi-cho/awesome-gpt4-wbesite?

**Comment by uellenberg** [comment]
> True. The current website is just the markdown converted to plain HTML. Would you like to contribute by adding some styles to https://github.com/radi-cho/awesome-gpt4-wbesite?
@radi-cho 

I didn't realize it was open-source. I've made https://github.com/radi-cho/awesome-gpt4-wbesite/pull/1.

**Comment by radi-cho** [comment]
Thank you very much for your willingness to contribute! Will continue communication on https://github.com/radi-cho/awesome-gpt4-wbesite/pull/1.
